name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - ${gcp_branch}

jobs:
  push_to_registry:
    name: Build Backend API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Create config.json
        run: |
          echo '{
            "REACT_APP_BACKEND_URL": "${gcp_backend_url}"
          }' > build/config.json

      - name: Setup GCP Authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: $${{ secrets.GCP_SA_KEY }}

      - name: Upload build folder to GCP bucket
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'build'
          destination: ${gcp_bucket_name}
          parent: false
          headers: |-
            cache-control: no-cache, no-store, max-age=0, must-revalidate
          process_gcloudignore: false


